# Generated by Django 4.0.1 on 2023-04-14 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.FileField(upload_to='static/messages')),
                ('first_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_account', to=settings.AUTH_USER_MODEL)),
                ('second_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
