# Generated by Django 4.2 on 2023-05-21 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatmessage',
            name='connected_to_chat_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatmessage',
            name='connected_to_chat_second',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='privatmessage',
            name='who_start_stream',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='UnreadMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_unread', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unread', to=settings.AUTH_USER_MODEL)),
                ('receiver_accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_unread', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_room', to='app.privatmessage')),
            ],
        ),
    ]
