# Generated by Django 4.2 on 2023-05-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_privatmessage_connected_to_chat_first_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatmessage',
            name='connected_to_chat_first',
        ),
        migrations.RemoveField(
            model_name='privatmessage',
            name='connected_to_chat_second',
        ),
        migrations.AddField(
            model_name='privatmessage',
            name='connected_to_chat',
            field=models.CharField(default='', max_length=120),
        ),
    ]
