# Generated by Django 4.2 on 2023-05-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo',
            field=models.ImageField(blank=True, upload_to='static/user_photo'),
        ),
    ]
